---
title: "p8105_hw6_mm6410"
author: "Mahdi Maktabi"
date: "2024-12-01"
output: github_document
---

```{r, message=FALSE}
library(tidyverse)
library(modelr)
```

## Problem 1

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
weather_df =
  weather_df |>
  bootstrap(5000) |> 
  mutate(
    models = map(strap, \(df) lm(tmax ~ tmin, data = df)),
    log_beta = map_dbl(models, ~ {
      coefs = broom::tidy(.x)
      log(coefs$estimate[1] * coefs$estimate[2])
    }),
    glance = map(models, broom::glance)
  )
```

### Plotting the R-Squared Distribution

```{r}
weather_df |> 
  select(strap, .id, glance) |> 
  unnest(glance) |> 
  select(.id, r.squared) |> 
  ggplot(aes(x = r.squared)) +
  geom_density()

weather_df |> 
  select(strap, .id, glance) |> 
  unnest(glance) |> 
  select(.id, r.squared) |> 
  pull(r.squared) |> 
  mean()
```

We can see from the density plot of the R-squared estimates that it is normally distributed. The mean of the R-squared estimates is 0.911. 

### Plotting the log($\hat{\beta}_{0}$ * $\hat{\beta}_{1}$)

```{r}
weather_df |> 
  ggplot(aes(x = log_beta)) +
  geom_density()
```

